displacement_processing_node:
  ros__parameters:
    polynomial_order: 1  # 다항식 차수

    # 센서 0의 캘리브레이션 계수
    sensor0:
      a: 0.0
      b: 0.0
      c: 0.0
      d: 0.0
      e: 1.0
      f: 0.0

    # 센서 1의 캘리브레이션 계수
    sensor1:
      a: 0.0
      b: 0.0
      c: 0.0
      d: 0.0
      e: 0.0
      f: 0.0

    # 센서 2의 캘리브레이션 계수
    sensor2:
      a: 0.0
      b: 0.0
      c: 0.0
      d: 0.0
      e: 0.0
      f: 0.0

    # 센서 3의 캘리브레이션 계수
    sensor3:
      a: 0.0
      b: 0.0
      c: 0.0
      d: 0.0
      e: 0.0
      f: 0.0


    # 센서 4의 캘리브레이션 계수
    sensor4:
      a: 0.0
      b: 0.0
      c: 0.0
      d: 0.0
      e: 0.0
      f: 0.0

    # 센서 5의 캘리브레이션 계수
    sensor5:
      a: 0.0
      b: 0.0
      c: 0.0
      d: 0.0
      e: 0.0
      f: 0.0

    # 센서 6의 캘리브레이션 계수
    sensor6:
      a: 0.0
      b: 0.0
      c: 0.0
      d: 0.0
      e: 0.0
      f: 0.0

    # 센서 7의 캘리브레이션 계수
    sensor7:
      a: 0.0
      b: 0.0
      c: 0.0
      d: 0.0
      e: 0.0
      f: 0.0

    # 센서 8의 캘리브레이션 계수
    sensor8:
      a: 0.0
      b: 0.0
      c: 0.0
      d: 0.0
      e: 0.0
      f: 0.0

      # 센서 9의 캘리브레이션 계수
    sensor9:
      a: 0.0
      b: 0.0
      c: 0.0
      d: 0.0
      e: 0.0
      f: 0.0


